/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import info5001.university.example.CourseCatalog.Course;
import info5001.university.example.CourseSchedule.CourseSchedule;
import info5001.university.example.Department.Department;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class RegisterCourse extends javax.swing.JPanel {
private JPanel UserProcessContainer;
private Department department;
    
    
    
public RegisterCourse(JPanel UserProcessContainer, Department department) {
        initComponents();
        this.UserProcessContainer= UserProcessContainer;
        this.department=department;
        populateTable();
    }
    /**
     * Creates new form RegisterCourse
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnViewCourseOffer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblterm = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseOffer = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnViewCourseLoad = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel2.setText("Select Term");

        btnViewCourseOffer.setText("View Course Offer");
        btnViewCourseOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseOfferActionPerformed(evt);
            }
        });

        jLabel1.setText("Register Course");

        tblterm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Term"
            }
        ));
        jScrollPane3.setViewportView(tblterm);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(304, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnViewCourseOffer)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewCourseOffer)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        tblCourseOffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Course Number", "Total Credits", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblCourseOffer);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnViewCourseLoad.setText("View Course Load");
        btnViewCourseLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseLoadActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewCourseLoad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewCourseLoad)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCourseOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseOfferActionPerformed
        // TODO add your handling code here:
         int selectedRow=tblterm.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first to view details!","Warning",JOptionPane.WARNING_MESSAGE);
            
        }
        else{
            String termName=(String)tblterm.getValueAt(selectedRow, 0);
            DefaultTableModel dtm=(DefaultTableModel) tblCourseOffer.getModel();
        dtm.setRowCount(0);
        CourseSchedule courseSchedule= department.getCourseSchedule(termName);
        ArrayList<Course> crsList=  department.getCourseCatalog().getCourseList();
        for(Course course:crsList){
            Object[] row= new Object[4];
            row[0]=course.getName();
            row[1]=course.getCOurseNumber();
            row[2]=course.getCredits();
            row[3]=course;
            dtm.addRow(row);
            
            
            
        }
            
        }
    }//GEN-LAST:event_btnViewCourseOfferActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblCourseOffer.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first to view details!","Warning",JOptionPane.WARNING_MESSAGE);
            
        }
        else{
            Course course=(Course)tblCourseOffer.getValueAt(selectedRow, 3);
            department.getStudentDirectory().findStudent("123").newCourseLoad(course);
            JOptionPane.showMessageDialog(null, "Course added successfully");
    }//GEN-LAST:event_btnAddActionPerformed
    }
    private void btnViewCourseLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseLoadActionPerformed
        // TODO add your handling code here:
        ViewCourseLoad panel=new ViewCourseLoad(UserProcessContainer, department);

            UserProcessContainer.add("ViewCourseLoad", panel);
            CardLayout layout= (CardLayout) UserProcessContainer.getLayout();
            layout.next(UserProcessContainer);
    }//GEN-LAST:event_btnViewCourseLoadActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        UserProcessContainer.remove(this);
        CardLayout layout= (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    
    
    private void populateTable(){
        DefaultTableModel dtm=(DefaultTableModel) tblterm.getModel();
        dtm.setRowCount(0);
        HashMap<String, CourseSchedule> mastercoursecatalog= department.getTerm();
      Set<String> termName=  mastercoursecatalog.keySet();
        for(String name:termName){
            Object[] row= new Object[1];
            row[0]=name;
        dtm.addRow(row);
            
            
            
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewCourseLoad;
    private javax.swing.JButton btnViewCourseOffer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tblCourseOffer;
    private javax.swing.JTable tblterm;
    // End of variables declaration//GEN-END:variables
}
